version: '3.7'

volumes:
  db: ~

services:

  nginx:
    image: nginx:mainline-alpine
    restart: on-failure
    volumes:
      - './:/var/www/:cached'
      - './.docker/nginx/nginx.conf:/etc/nginx/nginx.conf'
      - './.docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - "0.0.0.0:8009:80"
    links:
      - php
    depends_on:
      - php
  php:
    build: ./.docker/php
    volumes:
      - './:/var/www/:cached'
      - '~/.ssh/:/root/.ssh:ro'
      - './.docker/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini'
    environment:
      HOSTNAME: db
      SITE_URL: http://0.0.0.0:8009
      MYSQL_DATABASE: booking_db
      MYSQL_USER: booking-user
      MYSQL_PASSWORD: M!Aq12xjcDtLT#Zw
      MYSQL_ROOT_PASSWORD: 'secret'

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: booking_db
      MYSQL_USER: booking-user
      MYSQL_PASSWORD: M!Aq12xjcDtLT#Zw
      MYSQL_ROOT_PASSWORD: 'secret'
    volumes:
      - db9:/var/lib/mysql
      - './.docker/provision-db.sh:/tmp/provision-db.sh'
    ports:
      - "0.0.0.0:13309:3306"

networks:
  default:
    external:
      name: backoffice_stack_network
